/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
import java.awt.Image;
import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ApplicantSignup extends javax.swing.JFrame {

    /**
     * Creates new form ApplicantSignup
     */
    
//    public void mainImageScale() {
//        ImageIcon img= new ImageIcon("resources/add_user.png");
//        Image toScale= img.getImage();
//        Image scaledImage= toScale.getScaledInstance(signupImage.getWidth(),                                    signupImage.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon image= new ImageIcon(scaledImage);
//        signupImage.setIcon(image);
//    }
    
    public ApplicantSignup() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        applyLabel = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtFatherName = new javax.swing.JTextField();
        textGender = new javax.swing.JComboBox<>();
        textAddress = new javax.swing.JTextField();
        textCnic = new javax.swing.JTextField();
        applyBtn = new javax.swing.JButton();
        textEmail = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textBp = new javax.swing.JTextField();
        textDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        applyLabel.setBackground(new java.awt.Color(0, 51, 0));
        applyLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        applyLabel.setForeground(new java.awt.Color(204, 255, 204));
        applyLabel.setText("Apply for Passport");

        txtFullName.setBackground(new java.awt.Color(0, 51, 0));
        txtFullName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(204, 255, 204));
        txtFullName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Full Name: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(204, 255, 204))); // NOI18N

        txtFatherName.setBackground(new java.awt.Color(0, 51, 0));
        txtFatherName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFatherName.setForeground(new java.awt.Color(204, 255, 204));
        txtFatherName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Father Name: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(204, 255, 204))); // NOI18N

        textGender.setBackground(new java.awt.Color(0, 51, 0));
        textGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textGender.setForeground(new java.awt.Color(204, 255, 204));
        textGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        textGender.setBorder(null);
        textGender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textGenderActionPerformed(evt);
            }
        });

        textAddress.setBackground(new java.awt.Color(0, 51, 0));
        textAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textAddress.setForeground(new java.awt.Color(204, 255, 204));
        textAddress.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(204, 255, 204))); // NOI18N

        textCnic.setBackground(new java.awt.Color(0, 51, 0));
        textCnic.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textCnic.setForeground(new java.awt.Color(204, 255, 204));
        textCnic.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CNIC: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(204, 255, 204))); // NOI18N

        applyBtn.setBackground(new java.awt.Color(51, 102, 0));
        applyBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        applyBtn.setForeground(new java.awt.Color(204, 255, 204));
        applyBtn.setText("Apply");
        applyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });

        textEmail.setBackground(new java.awt.Color(0, 51, 0));
        textEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textEmail.setForeground(new java.awt.Color(204, 255, 204));
        textEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(204, 255, 204))); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 51, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 255, 204));
        jButton2.setText("< Back");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_user_400x400.png"))); // NOI18N

        textBp.setBackground(new java.awt.Color(0, 51, 0));
        textBp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textBp.setForeground(new java.awt.Color(204, 255, 204));
        textBp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Birth Place: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(204, 255, 204))); // NOI18N

        textDate.setBackground(new java.awt.Color(0, 51, 0));
        textDate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date of Birth", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(204, 255, 204))); // NOI18N
        textDate.setForeground(new java.awt.Color(204, 255, 204));
        textDate.setDateFormatString("MM-d-YYYY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(applyBtn)
                                .addGap(189, 189, 189))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textEmail)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textCnic)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(textGender, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(textDate, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textAddress))
                                .addGap(20, 20, 20)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(applyLabel)
                            .addGap(95, 95, 95)))
                    .addComponent(textBp)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(applyLabel)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textGender, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(textDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textCnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(applyBtn)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBtnActionPerformed
        // TODO add your handling code here:
        
        boolean isInsert;
        
        String fullName= txtFullName.getText(),
                fatherName= txtFatherName.getText(),
                email= textEmail.getText(),
                gender= String.valueOf(textGender.getSelectedItem()),
                address= textAddress.getText(),
                cnic= textCnic.getText(),
                birthPlace= textBp.getText();
        
        SimpleDateFormat dateFormat= new SimpleDateFormat("MM-d-YYYY");
        String dob= dateFormat.format(textDate.getDate());
        
        System.out.println(dob);
        
        DBConnection db= new DBConnection();
        
        if(fullName.equals("") || fatherName.equals("") || email.equals("") || gender.equals("") || dob.equals("") || address.equals("") || cnic.equals("") || birthPlace.equals("")) {
            JOptionPane.showMessageDialog(null, "Error: Fill all fields!");
        }
        else {
            String query= "INSERT INTO Applicants(fullName, fatherName, email, gender, dob, applicantAddress, cnic, birthPlace, applicantStatus) VALUES ('"+fullName+"', '"+fatherName+"', '"+email+"', '"+gender+"', '"+dob+"', '"+address+"', '"+cnic+"', '"+birthPlace+"', 'Pending')";
            
            isInsert= db.insertData(query);
            
            if(isInsert == true) {
                String idFetchQuery= "SELECT applicantID FROM Applicants WHERE email= '"+email+"'";
                try {
                    ResultSet idFetch= db.selectData(idFetchQuery);
                    if(idFetch.next()) {
                        JOptionPane.showMessageDialog(null, "You Applied Sucessfully!\n"
                        + "You Application ID is: "+ idFetch.getInt(1));
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            else if(isInsert == false) {
                JOptionPane.showMessageDialog(null, "Unknown Error Occured!");
            }
        }
    }//GEN-LAST:event_applyBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LoginAs aslogin = new LoginAs();
        aslogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textGenderActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textGenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicantSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicantSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicantSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicantSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicantSignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyBtn;
    private javax.swing.JLabel applyLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textBp;
    private javax.swing.JTextField textCnic;
    private com.toedter.calendar.JDateChooser textDate;
    private javax.swing.JTextField textEmail;
    private javax.swing.JComboBox<String> textGender;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtFullName;
    // End of variables declaration//GEN-END:variables
}
